[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib","protocol-v2/lib"]
include_paths = ["node_modules"]

remappings = [
    "forge-std/=node_modules/forge-std/src/",
     "ds-test/=node_modules/ds-test/src/",
    "@openzeppelin/=protocol-v2/lib/openzeppelin-contracts/",
]


[detectors]
exclude = []
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""

